export const HOME_MENU = [
    {
        "name": "theme-clickstore",
        "menus": [
            {
                "title": "Telco e-Load",
                "url": "/e-load",
                "icon": "../assets/img/menu-icons/mobile.svg",
                "disabled": false,
                "activated": true,
                "isPNG": false,
            },
            {
                "title": "Gaming Pins",
                "url": "/gaming-pins",
                "icon": "../assets/img/menu-icons/controller.svg",
                "disabled": true,
                "activated": true,
                "isPNG": false,
            },
            {
                "title": "Pop Tv Pins",
                "url": "/e-pins",
                "icon": "../assets/img/menu-icons/poptv.png",
                "disabled": true,
                "activated": true,
                "isPNG": true,
            },
            {
                "title": "Radius ISP",
                "url": "/isp",
                "icon": "../assets/img/menu-icons/radius.png",
                "disabled": false,
                "activated": true,
                "isPNG": true,
            },
            {
                "title": "Market Place",
                "url": "/market-place",
                "icon": "../assets/img/menu-icons/store.svg",
                "disabled": false,
                "activated": true,
                "isPNG": false,
            },
            {
                "title": "Bills Payment",
                "url": "/bills-payment",
                "icon": "../assets/img/menu-icons/bills.svg",
                "disabled": true,
                "activated": true,
                "isPNG": false,
            },
            {
                "title": "Remittance",
                "url": "/remittance",
                "icon": "../assets/img/menu-icons/remittance.svg",
                "disabled": true,
                "activated": true,
                "isPNG": false,
            },
            {
                "title": "Travel and Booking",
                "url": "/travel-and-booking",
                "icon": "../assets/img/menu-icons/travel.svg",
                "disabled": true,
                "activated": true,
                "isPNG": false,
            },
            {
                "title": "Loans",
                "url": "/loans",
                "icon": "../assets/img/menu-icons/loan.svg",
                "disabled": true,
                "activated": true,
                "isPNG": false,
            },
            {
                "title": "Government Billers",
                "url": "/government-billers",
                "icon": "../assets/img/menu-icons/government.svg",
                "disabled": true,
                "activated": true,
                "isPNG": false,
            },
            {
                "title": "Report History",
                "url": "/report-history",
                "icon": "../assets/img/menu-icons/report.svg",
                "disabled": false,
                "activated": true,
                "isPNG": false,
            },
        ]
    },
    {
        "name": "theme-vitalize",
        "menus": [
            {
                "title": "Telco e-Load",
                "url": "/e-load",
                "icon": "../assets/img/menu-icons/mobile.svg",
                "disabled": false,
                "activated": true,
                "isPNG": false,
            },
            {
                "title": "Report History",
                "url": "/report-history",
                "icon": "../assets/img/menu-icons/report.svg",
                "disabled": false,
                "activated": true,
                "isPNG": false,
            },
        ]
    },
    {
        "name": "theme-peso",
        "menus": [
            {
                "title": "Telco e-Load",
                "url": "/e-load",
                "icon": "../assets/img/menu-icons/mobile.svg",
                "disabled": false,
                "activated": true,
                "isPNG": false,
            },
            {
                "title": "Gaming Pins",
                "url": "/gaming-pins",
                "icon": "../assets/img/menu-icons/controller.svg",
                "disabled": true,
                "activated": true,
                "isPNG": false,
            },
            {
                "title": "Pop Tv Pins",
                "url": "/e-pins",
                "icon": "../assets/img/menu-icons/poptv.png",
                "disabled": true,
                "activated": true,
                "isPNG": true,
            },
            {
                "title": "Radius ISP",
                "url": "/isp",
                "icon": "../assets/img/menu-icons/radius.png",
                "disabled": true,
                "activated": true,
                "isPNG": true,
            },
            {
                "title": "Market Place",
                "url": "/market-place",
                "icon": "../assets/img/menu-icons/store.svg",
                "disabled": false,
                "activated": true,
                "isPNG": false,
            },
            {
                "title": "Bills Payment",
                "url": "/bills-payment",
                "icon": "../assets/img/menu-icons/bills.svg",
                "disabled": true,
                "activated": true,
                "isPNG": false,
            },
            {
                "title": "Remittance",
                "url": "/remittance",
                "icon": "../assets/img/menu-icons/remittance.svg",
                "disabled": true,
                "activated": true,
                "isPNG": false,
            },
            {
                "title": "Travel and Booking",
                "url": "/travel-and-booking",
                "icon": "../assets/img/menu-icons/travel.svg",
                "disabled": true,
                "activated": true,
                "isPNG": false,
            },
            {
                "title": "Loans",
                "url": "/loans",
                "icon": "../assets/img/menu-icons/loan.svg",
                "disabled": true,
                "activated": true,
                "isPNG": false,
            },
            {
                "title": "Government Billers",
                "url": "/government-billers",
                "icon": "../assets/img/menu-icons/government.svg",
                "disabled": true,
                "activated": true,
                "isPNG": false,
            },
            {
                "title": "Report History",
                "url": "/report-history",
                "icon": "../assets/img/menu-icons/report.svg",
                "disabled": false,
                "activated": true,
                "isPNG": false,
            },
        ]
    }
]